### PR TITLE
fix #136

### LINKED ISSUE #136: PHP Parse error:  syntax error, unexpected '=', expecting ')'
I'm building a docker image for OTS.

Testing the image, while parsing the references the given error is raised.

    ots_1    | PHP Parse error:  syntax error, unexpected '=', expecting ')' in /project/ots/module/ReferencesConversion/src/ReferencesConversion/Model/Converter/References.php on line 445

I'm not an expert in PHP, but it seems it is not a valid sintaxe in PHP 5.4.16

https://github.com/pkp/ots/blob/7900ecc585d2666d5213f8a06b189bec935c2c2f/module/ReferencesConversion/src/ReferencesConversion/Model/Converter/References.php#L444-L447

### PR DESCRIPTION
**Pull request by fabiobatalha**

### CODE REVIEW

**Comment by axfelix** [comment]
Hi Fabio,

I'm honestly not sure I want to merge anything with the explicit purpose of supporting such an old version of PHP -- I'm planning to migrate us to supporting 7.x only by April 2019. Why do you need 5.4?

**Comment by fabiobatalha** [comment]
I'm using the default PHP distro version of CentOS 7.

I think this change is not a problem for PHP 7.X.

**Comment by axfelix** [comment]
OK, but we *will* be adding backwards incompatible changes without worrying about it beginning later this year. I'll merge this for now, but it should be a very temporary solution. CentOS 7's default PHP is ancient.

**Comment by fabiobatalha** [comment]
don't need to. I will upgrade the PHP to PHP 7.

**Pull request closed without merging**
